# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    enp1s0:
      dhcp4: true
    enp2s0:
      dhcp4: no
      addresses:
        - 192.168.5.140/25
      nameservers:
        addresses:
          - 1.1.1.1

